### ISSUE TITLE
能不能自己打镜像？能否提供Dockerfile

### ISSUE THREAD

**Issue by MrRohwei** [modelscope/FunASR#2010]
#### What is your question?
如题，官方的镜像启动后还需要去镜像内部执行脚本，想自己自定义Dockerfile然后Docker容器启动的时候自动执行服务端脚本。
请问是否支持这种方式呢？

#### What's your environment?

 - OS (e.g., Linux): Ubuntu或Centos
 - FunASR Version (e.g., 1.0.0): funasr-runtime-sdk-online-cpu-0.1.10

**Comment by purerosefallen** [comment]
```dockerfile
FROM registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.10
WORKDIR /workspace/FunASR/runtime
RUN chmod +x ./run_server_2pass.sh && \
    sed -i 's/&$//g' ./run_server_2pass.sh
CMD bash ./run_server_2pass.sh --download-model-dir /workspace/models --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx --model-dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onn --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst --itn-dir thuduj12/fst_itn_zh
```

This is what I'm using

**Comment by MrRohwei** [comment]
谢谢，我已经通过docker-compose实现了 @purerosefallen 
```yml
version: '3'

services:
  funasr:
    image: tw-asr:online-cpu-0.1.10
    container_name: test_funasr
    restart: always
    command: >
      /bin/bash -c '
      (
        cd FunASR/runtime && \
        nohup bash run_server_2pass.sh \
        --vad-dir /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
        --model-dir /workspace/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
        --punc-dir /workspace/models/damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx \
        --lm-dir /workspace/models/damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
        --itn-dir /workspace/models/thuduj12/fst_itn_zh \
        --hotword /workspace/models/hotwords.txt > log.txt 2>&1 &
      tail -f /dev/null
      )
      '
    ports:
      - "10096:10095"
    volumes:
      - /usr/local/funasr/funasr-runtime-resources/models:/workspace/models
    privileged: true
    networks:
      - app-net

networks:
  app-net:
```
